trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pythonVersions: '["3.12", "3.13", "3.14"]'  
  mode: 'emulate'
  # mode: 'execute'

###################################################################
# CI Stage                                                        #
###################################################################
stages:
- stage: CI
  displayName: CI
  jobs:
  - job: Build
    displayName: 'Build the app'
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - script: echo "Task Succeeded"
      condition: and(succeeded(), eq(variables['mode'], 'emulate'))
      displayName: 'Build emulation'

  - job: TestMatrix
    displayName: 'Test with Multiple Python Versions'
    strategy:
      matrix:
        Python312:
          pythonVersion: '3.12'
        Python313:
          pythonVersion: '3.13'
        Python314:
          pythonVersion: '3.14'
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - task: UsePythonVersion@0
      displayName: 'Set up Python $(pythonVersion)'
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true
    
    - script: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install pytest pytest-cov
      displayName: 'Install dependencies'
    
    - script: |
        cd server
        python -m pytest test_app.py -v --tb=short --junitxml=test-results.xml --cov=app --cov-report=term-missing --cov-report=xml
      displayName: 'Run tests with pytest'
    
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'server/test-results.xml'
        testRunTitle: 'Python $(pythonVersion) Tests'
        failTaskOnFailedTests: true
    
    - task: PublishCodeCoverageResults@2
      displayName: 'Upload coverage reports'
      condition: eq(variables['pythonVersion'], '3.12')
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'server/coverage.xml'
        reportDirectory: 'server/htmlcov'
        failIfCoverageEmpty: false

###################################################################
# Dev Stage                                                       #
###################################################################
- stage: Dev
  displayName: Dev
  dependsOn: CI
  variables:
    slot: Dev

  jobs:
  - deployment: DeployWeb
    displayName: Deploy and test
    # creates an environment if it doesn't exist
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          
          - download: current
            artifact: $(ArtifactName)

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Becep Template Execution emulation'

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Deploy Container App emulation'

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Playwright UI Tests emulation'

###################################################################
# QA Stage                                                        #
###################################################################
- stage: QA
  displayName: QA
  dependsOn: Dev
  variables:
    slot: QA

  jobs:
  - deployment: DeployWeb
    displayName: Deploy and test
    # creates an environment if it doesn't exist
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
          
          - download: current
            artifact: $(ArtifactName)

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Becep Template Execution emulation'

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Deploy Container App emulation'

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Playwright UI Tests emulation'

###################################################################
# Production  Stage                                               #
###################################################################
- stage: Production
  displayName: Production
  dependsOn: QA
  variables:
    slot: Production

  jobs:
  - deployment: DeployWeb
    displayName: Deploy
    # creates an environment if it doesn't exist
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          
          - download: current
            artifact: $(ArtifactName)

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Becep Template Execution emulation'

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Deploy Container App emulation'

          - script: echo "Task Succeeded"
            condition: and(succeeded(), eq(variables['mode'], 'emulate'))
            displayName: 'Playwright UI Tests emulation'

