##################################################################################################################
# Build and deploy via Azure Pipelines
# Refer to https://dev.azure.com/PUnlimited/PetsWorkshop/_boards/board/t/PetsWorkshop%20Team/Stories?workitem=642
# 
# This pipeline deploys the Pets Workshop application to Dev, QA, and Production environments.
# Each environment is deployed to a separate resource group (rg-Dev, rg-QA, rg-Production).
# The pipeline uses Bicep templates from the infra folder to provision Azure resources.
# 
# Prerequisites:
# - Azure service connection named 'AzureServiceConnection' (or update the variable)
# - Environments configured in Azure DevOps: Dev, QA, Production
# - Appropriate permissions to deploy at subscription scope
##################################################################################################################

trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pythonVersions: '["3.12", "3.13", "3.14"]'
  azureSubscription: 'AzureServiceConnection' # Update with your Azure service connection name
  location: 'eastus' # Update with your preferred Azure location

###################################################################
# CI Stage                                                        #
###################################################################
stages:
- stage: CI
  displayName: CI
  jobs:
  - job: Build
    displayName: 'Build and publish container images'
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - task: Docker@2
      displayName: 'Build client Docker image'
      inputs:
        command: build
        repository: 'client'
        dockerfile: '$(Build.SourcesDirectory)/client/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    
    - task: Docker@2
      displayName: 'Build server Docker image'
      inputs:
        command: build
        repository: 'server'
        dockerfile: '$(Build.SourcesDirectory)/server/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Bicep templates'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/infra'
        artifact: 'infra'
        publishLocation: 'pipeline'

  - job: TestMatrix
    displayName: 'Test with Multiple Python Versions'
    strategy:
      matrix:
        Python312:
          pythonVersion: '3.12'
        Python313:
          pythonVersion: '3.13'
        Python314:
          pythonVersion: '3.14'
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - task: UsePythonVersion@0
      displayName: 'Set up Python $(pythonVersion)'
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true
    
    - script: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install pytest pytest-cov
      displayName: 'Install dependencies'
    
    - script: |
        cd server
        python -m pytest test_app.py -v --tb=short --junitxml=test-results.xml --cov=app --cov-report=term-missing --cov-report=xml
      displayName: 'Run tests with pytest'
    
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'server/test-results.xml'
        testRunTitle: 'Python $(pythonVersion) Tests'
        failTaskOnFailedTests: true
    
    - task: PublishCodeCoverageResults@2
      displayName: 'Upload coverage reports'
      condition: eq(variables['pythonVersion'], '3.12')
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'server/coverage.xml'
        reportDirectory: 'server/htmlcov'
        failIfCoverageEmpty: false

###################################################################
# Dev Stage                                                       #
###################################################################
- stage: Dev
  displayName: Dev
  dependsOn: CI
  variables:
    environmentName: 'Dev'
    resourceGroupName: 'Dev'

  jobs:
  - deployment: DeployInfrastructure
    displayName: 'Deploy infrastructure'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: 'Checkout code'
          
          - download: current
            artifact: infra
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Deploy Bicep template'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Deploy the Bicep template at subscription scope
                az deployment sub create \
                  --name "$(environmentName)-$(Build.BuildId)" \
                  --location $(location) \
                  --template-file $(Pipeline.Workspace)/infra/main.bicep \
                  --parameters environmentName=$(environmentName) \
                  --parameters location=$(location) \
                  --parameters clientExists=false \
                  --parameters serverExists=false \
                  --parameters principalId=$(az ad signed-in-user show --query id -o tsv) \
                  --parameters principalType=User
                
                # Get outputs
                ACR_ENDPOINT=$(az deployment sub show \
                  --name "$(environmentName)-$(Build.BuildId)" \
                  --query properties.outputs.AZURE_CONTAINER_REGISTRY_ENDPOINT.value -o tsv)
                
                echo "##vso[task.setvariable variable=acrEndpoint;isOutput=true]$ACR_ENDPOINT"
                echo "Container Registry Endpoint: $ACR_ENDPOINT"
            name: deployBicep
  
  - job: PushImages
    displayName: 'Push container images to ACR'
    dependsOn: DeployInfrastructure
    variables:
      acrEndpoint: $[ dependencies.DeployInfrastructure.outputs['DeployInfrastructure.deployBicep.acrEndpoint'] ]
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - task: AzureCLI@2
      displayName: 'Login to ACR and push images'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Login to ACR
          az acr login --name $(acrEndpoint)
          
          # Build and push client image
          docker build -t $(acrEndpoint)/client:$(Build.BuildId) -t $(acrEndpoint)/client:latest ./client
          docker push $(acrEndpoint)/client:$(Build.BuildId)
          docker push $(acrEndpoint)/client:latest
          
          # Build and push server image
          docker build -t $(acrEndpoint)/server:$(Build.BuildId) -t $(acrEndpoint)/server:latest ./server
          docker push $(acrEndpoint)/server:$(Build.BuildId)
          docker push $(acrEndpoint)/server:latest
  
  - deployment: UpdateContainerApps
    displayName: 'Update container apps'
    dependsOn: 
      - DeployInfrastructure
      - PushImages
    environment: 'Dev'
    variables:
      acrEndpoint: $[ dependencies.DeployInfrastructure.outputs['DeployInfrastructure.deployBicep.acrEndpoint'] ]
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: 'Checkout code'
          
          - download: current
            artifact: infra
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Update container apps'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Redeploy with updated images
                az deployment sub create \
                  --name "$(environmentName)-update-$(Build.BuildId)" \
                  --location $(location) \
                  --template-file $(Pipeline.Workspace)/infra/main.bicep \
                  --parameters environmentName=$(environmentName) \
                  --parameters location=$(location) \
                  --parameters clientExists=true \
                  --parameters serverExists=true \
                  --parameters principalId=$(az ad signed-in-user show --query id -o tsv) \
                  --parameters principalType=User

###################################################################
# QA Stage                                                        #
###################################################################
- stage: QA
  displayName: QA
  dependsOn: Dev
  variables:
    environmentName: 'QA'
    resourceGroupName: 'QA'

  jobs:
  - deployment: DeployInfrastructure
    displayName: 'Deploy infrastructure'
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: 'Checkout code'
          
          - download: current
            artifact: infra
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Deploy Bicep template'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Deploy the Bicep template at subscription scope
                az deployment sub create \
                  --name "$(environmentName)-$(Build.BuildId)" \
                  --location $(location) \
                  --template-file $(Pipeline.Workspace)/infra/main.bicep \
                  --parameters environmentName=$(environmentName) \
                  --parameters location=$(location) \
                  --parameters clientExists=false \
                  --parameters serverExists=false \
                  --parameters principalId=$(az ad signed-in-user show --query id -o tsv) \
                  --parameters principalType=User
                
                # Get outputs
                ACR_ENDPOINT=$(az deployment sub show \
                  --name "$(environmentName)-$(Build.BuildId)" \
                  --query properties.outputs.AZURE_CONTAINER_REGISTRY_ENDPOINT.value -o tsv)
                
                echo "##vso[task.setvariable variable=acrEndpoint;isOutput=true]$ACR_ENDPOINT"
                echo "Container Registry Endpoint: $ACR_ENDPOINT"
            name: deployBicep
  
  - job: PushImages
    displayName: 'Push container images to ACR'
    dependsOn: DeployInfrastructure
    variables:
      acrEndpoint: $[ dependencies.DeployInfrastructure.outputs['DeployInfrastructure.deployBicep.acrEndpoint'] ]
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - task: AzureCLI@2
      displayName: 'Login to ACR and push images'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Login to ACR
          az acr login --name $(acrEndpoint)
          
          # Build and push client image
          docker build -t $(acrEndpoint)/client:$(Build.BuildId) -t $(acrEndpoint)/client:latest ./client
          docker push $(acrEndpoint)/client:$(Build.BuildId)
          docker push $(acrEndpoint)/client:latest
          
          # Build and push server image
          docker build -t $(acrEndpoint)/server:$(Build.BuildId) -t $(acrEndpoint)/server:latest ./server
          docker push $(acrEndpoint)/server:$(Build.BuildId)
          docker push $(acrEndpoint)/server:latest
  
  - deployment: UpdateContainerApps
    displayName: 'Update container apps'
    dependsOn: 
      - DeployInfrastructure
      - PushImages
    environment: 'QA'
    variables:
      acrEndpoint: $[ dependencies.DeployInfrastructure.outputs['DeployInfrastructure.deployBicep.acrEndpoint'] ]
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: 'Checkout code'
          
          - download: current
            artifact: infra
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Update container apps'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Redeploy with updated images
                az deployment sub create \
                  --name "$(environmentName)-update-$(Build.BuildId)" \
                  --location $(location) \
                  --template-file $(Pipeline.Workspace)/infra/main.bicep \
                  --parameters environmentName=$(environmentName) \
                  --parameters location=$(location) \
                  --parameters clientExists=true \
                  --parameters serverExists=true \
                  --parameters principalId=$(az ad signed-in-user show --query id -o tsv) \
                  --parameters principalType=User

###################################################################
# Production Stage                                                #
###################################################################
- stage: Production
  displayName: Production
  dependsOn: QA
  variables:
    environmentName: 'Production'
    resourceGroupName: 'Production'

  jobs:
  - deployment: DeployInfrastructure
    displayName: 'Deploy infrastructure'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: 'Checkout code'
          
          - download: current
            artifact: infra
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Deploy Bicep template'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Deploy the Bicep template at subscription scope
                az deployment sub create \
                  --name "$(environmentName)-$(Build.BuildId)" \
                  --location $(location) \
                  --template-file $(Pipeline.Workspace)/infra/main.bicep \
                  --parameters environmentName=$(environmentName) \
                  --parameters location=$(location) \
                  --parameters clientExists=false \
                  --parameters serverExists=false \
                  --parameters principalId=$(az ad signed-in-user show --query id -o tsv) \
                  --parameters principalType=User
                
                # Get outputs
                ACR_ENDPOINT=$(az deployment sub show \
                  --name "$(environmentName)-$(Build.BuildId)" \
                  --query properties.outputs.AZURE_CONTAINER_REGISTRY_ENDPOINT.value -o tsv)
                
                echo "##vso[task.setvariable variable=acrEndpoint;isOutput=true]$ACR_ENDPOINT"
                echo "Container Registry Endpoint: $ACR_ENDPOINT"
            name: deployBicep
  
  - job: PushImages
    displayName: 'Push container images to ACR'
    dependsOn: DeployInfrastructure
    variables:
      acrEndpoint: $[ dependencies.DeployInfrastructure.outputs['DeployInfrastructure.deployBicep.acrEndpoint'] ]
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - task: AzureCLI@2
      displayName: 'Login to ACR and push images'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Login to ACR
          az acr login --name $(acrEndpoint)
          
          # Build and push client image
          docker build -t $(acrEndpoint)/client:$(Build.BuildId) -t $(acrEndpoint)/client:latest ./client
          docker push $(acrEndpoint)/client:$(Build.BuildId)
          docker push $(acrEndpoint)/client:latest
          
          # Build and push server image
          docker build -t $(acrEndpoint)/server:$(Build.BuildId) -t $(acrEndpoint)/server:latest ./server
          docker push $(acrEndpoint)/server:$(Build.BuildId)
          docker push $(acrEndpoint)/server:latest
  
  - deployment: UpdateContainerApps
    displayName: 'Update container apps'
    dependsOn: 
      - DeployInfrastructure
      - PushImages
    environment: 'Production'
    variables:
      acrEndpoint: $[ dependencies.DeployInfrastructure.outputs['DeployInfrastructure.deployBicep.acrEndpoint'] ]
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: 'Checkout code'
          
          - download: current
            artifact: infra
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Update container apps'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Redeploy with updated images
                az deployment sub create \
                  --name "$(environmentName)-update-$(Build.BuildId)" \
                  --location $(location) \
                  --template-file $(Pipeline.Workspace)/infra/main.bicep \
                  --parameters environmentName=$(environmentName) \
                  --parameters location=$(location) \
                  --parameters clientExists=true \
                  --parameters serverExists=true \
                  --parameters principalId=$(az ad signed-in-user show --query id -o tsv) \
                  --parameters principalType=User

