##################################################################################################################
# Build and deploy via Azure Pipelines
# Refer to https://dev.azure.com/PUnlimited/PetsWorkshop/_boards/board/t/PetsWorkshop%20Team/Stories?workitem=642
# Multi-stage deployment with Bicep infrastructure deployment
##################################################################################################################

trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pythonVersions: '["3.12", "3.13", "3.14"]'
  
  # Azure Deployment Configuration
  azureServiceConnection: 'AzureServiceConnection' # Update with your service connection name
  azureSubscriptionId: '$(AZURE_SUBSCRIPTION_ID)' # Set this variable in pipeline variables or variable group
  azureLocation: 'westus' # Default Azure region for deployments
  
  # Deployment Parameters (common across environments)
  principalId: '$(AZURE_PRINCIPAL_ID)' # Set this variable in pipeline variables or variable group
  principalType: '$(AZURE_PRINCIPAL_TYPE)' # Set this variable (e.g., 'ServicePrincipal' or 'User')
  clientExists: false # Set to true if container app already exists
  serverExists: false # Set to true if container app already exists

###################################################################
# CI Stage                                                        #
###################################################################
stages:
- stage: CI
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build and Publish Artifacts'
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - script: |
        echo "##[section]Building application artifacts"
        echo "Build configuration: $(buildConfiguration)"
      displayName: 'Build application'
    
    # Publish Bicep templates and parameters as build artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Bicep templates'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/infra'
        ArtifactName: 'bicep-templates'
        publishLocation: 'Container'

  - job: TestMatrix
    displayName: 'Test with Multiple Python Versions'
    strategy:
      matrix:
        Python312:
          pythonVersion: '3.12'
        Python313:
          pythonVersion: '3.13'
        Python314:
          pythonVersion: '3.14'
    
    steps:
    - checkout: self
      displayName: 'Checkout code'
    
    - task: UsePythonVersion@0
      displayName: 'Set up Python $(pythonVersion)'
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true
    
    - script: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install pytest pytest-cov
      displayName: 'Install dependencies'
    
    - script: |
        cd server
        python -m pytest test_app.py -v --tb=short --junitxml=test-results.xml --cov=app --cov-report=term-missing --cov-report=xml
      displayName: 'Run tests with pytest'
    
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'server/test-results.xml'
        testRunTitle: 'Python $(pythonVersion) Tests'
        failTaskOnFailedTests: true
    
    - task: PublishCodeCoverageResults@2
      displayName: 'Upload coverage reports'
      condition: eq(variables['pythonVersion'], '3.12')
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'server/coverage.xml'
        reportDirectory: 'server/htmlcov'
        failIfCoverageEmpty: false

###################################################################
# Dev Stage                                                       #
###################################################################
- stage: Dev
  displayName: 'Deploy to Dev'
  dependsOn: CI
  condition: succeeded()
  variables:
    environmentName: 'Dev'
    resourceGroupName: 'Tailspin-Shelter-Dev'

  jobs:
  - deployment: DeployInfrastructure
    displayName: 'Deploy Infrastructure and Application'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          
          - download: current
            artifact: bicep-templates
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Deploy Bicep template to Dev'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "##[section]Deploying infrastructure to Dev environment"
                echo "Subscription: $(azureSubscriptionId)"
                echo "Location: $(azureLocation)"
                echo "Environment: $(environmentName)"
                
                # Deploy subscription-scoped Bicep template
                az deployment sub create \
                  --name "deploy-$(environmentName)-$(Build.BuildId)" \
                  --location "$(azureLocation)" \
                  --template-file "$(Pipeline.Workspace)/bicep-templates/main.bicep" \
                  --parameters \
                    environmentName="$(environmentName)" \
                    location="$(azureLocation)" \
                    principalId="$(principalId)" \
                    principalType="$(principalType)" \
                    clientExists=$(clientExists) \
                    serverExists=$(serverExists) \
                  --verbose
                
                echo "##[section]Deployment completed successfully"
                
                # Output deployment results
                az deployment sub show \
                  --name "deploy-$(environmentName)-$(Build.BuildId)" \
                  --query properties.outputs
          
          - script: |
              echo "##[section]Post-deployment validation for Dev"
              echo "Infrastructure deployed to resource group: $(resourceGroupName)"
              echo "Next steps: Deploy container applications"
            displayName: 'Post-deployment steps'

###################################################################
# QA Stage                                                        #
###################################################################
- stage: QA
  displayName: 'Deploy to QA'
  dependsOn: Dev
  condition: succeeded()
  variables:
    environmentName: 'QA'
    resourceGroupName: 'Tailspin-Shelter-QA'

  jobs:
  - deployment: DeployInfrastructure
    displayName: 'Deploy Infrastructure and Application'
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          
          - download: current
            artifact: bicep-templates
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Deploy Bicep template to QA'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "##[section]Deploying infrastructure to QA environment"
                echo "Subscription: $(azureSubscriptionId)"
                echo "Location: $(azureLocation)"
                echo "Environment: $(environmentName)"
                
                # Deploy subscription-scoped Bicep template
                az deployment sub create \
                  --name "deploy-$(environmentName)-$(Build.BuildId)" \
                  --location "$(azureLocation)" \
                  --template-file "$(Pipeline.Workspace)/bicep-templates/main.bicep" \
                  --parameters \
                    environmentName="$(environmentName)" \
                    location="$(azureLocation)" \
                    principalId="$(principalId)" \
                    principalType="$(principalType)" \
                    clientExists=$(clientExists) \
                    serverExists=$(serverExists) \
                  --verbose
                
                echo "##[section]Deployment completed successfully"
                
                # Output deployment results
                az deployment sub show \
                  --name "deploy-$(environmentName)-$(Build.BuildId)" \
                  --query properties.outputs
          
          - script: |
              echo "##[section]Post-deployment validation for QA"
              echo "Infrastructure deployed to resource group: $(resourceGroupName)"
              echo "Running smoke tests and validation"
            displayName: 'Post-deployment validation'
          
          - script: |
              echo "##[section]Placeholder for Playwright UI Tests"
              echo "TODO: Implement Playwright tests for QA environment"
            displayName: 'Run UI tests (placeholder)'

###################################################################
# Production Stage                                                #
###################################################################
- stage: Production
  displayName: 'Deploy to Production'
  dependsOn: QA
  condition: succeeded()
  variables:
    environmentName: 'Production'
    resourceGroupName: 'Tailspin-Shelter-Production'

  jobs:
  - deployment: DeployInfrastructure
    displayName: 'Deploy Infrastructure and Application'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          
          - download: current
            artifact: bicep-templates
            displayName: 'Download Bicep templates'
          
          - task: AzureCLI@2
            displayName: 'Deploy Bicep template to Production'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "##[section]Deploying infrastructure to Production environment"
                echo "Subscription: $(azureSubscriptionId)"
                echo "Location: $(azureLocation)"
                echo "Environment: $(environmentName)"
                
                # Deploy subscription-scoped Bicep template
                az deployment sub create \
                  --name "deploy-$(environmentName)-$(Build.BuildId)" \
                  --location "$(azureLocation)" \
                  --template-file "$(Pipeline.Workspace)/bicep-templates/main.bicep" \
                  --parameters \
                    environmentName="$(environmentName)" \
                    location="$(azureLocation)" \
                    principalId="$(principalId)" \
                    principalType="$(principalType)" \
                    clientExists=$(clientExists) \
                    serverExists=$(serverExists) \
                  --verbose
                
                echo "##[section]Deployment completed successfully"
                
                # Output deployment results
                az deployment sub show \
                  --name "deploy-$(environmentName)-$(Build.BuildId)" \
                  --query properties.outputs
          
          - script: |
              echo "##[section]Post-deployment validation for Production"
              echo "Infrastructure deployed to resource group: $(resourceGroupName)"
              echo "Verifying production deployment health"
            displayName: 'Post-deployment validation'
          
          - script: |
              echo "##[section]Production deployment complete"
              echo "Monitor application health and performance"
              echo "Application Insights and Log Analytics available for monitoring"
            displayName: 'Deployment summary'

